List<List<String>> dailyproblems = [
  [
    //Scars
    "https://www.hopkinsmedicine.org/sebin/z/d/scar.jpg",
    "If the scars are old, you’ll have to just live with them. But you can diminish them when they’re new – less than a year old, Baumann says. \n\nScars that are thin, flat, white and tissue paper-like can sometimes be treated with a Fraxel laser, which pokes small holes in the skin. \n\n“When it heals, the skin pulls together and is tighter,” Baumann explains. \n\nSteroid injections can soften and improve the appearance of new, thin keloid scars, which are raised, bumpy and flesh-colored; older ones may have to be surgically removed.\n\nRed scars can be treated with a vascular laser, which targets blood vessels, to tone down the color.\n\nAnd the pockmarks left by a bad bout of acne? Try Fraxel lasers and injectible fillers, such as Restylane, which stimulate collagen production to help fill in depressed areas. In some cases, they can be surgically removed by a plastic surgeon."
  ],
  [
    //Wrinkles
    "https://cdn.shopify.com/s/files/1/0100/3755/9332/articles/yora-journal-forehead-wrinkles-featured_1560x.jpg?v=1584612524",
    "Aloe Vera\n\n- Known for its healing properties and enriched Vitamin E content, applying aloe vera on the skin for 90 days continuously can help us get rid of the wrinkles. Aloe Vera helps us in getting rid of the dull skin too.\n\nEgg whites\n\n- Eggs can do wonders for our skin and the Vitamin and protein compound present in them can help avoid wrinkles. Egg whites help in tightening our skin and also absorbs excess sebum from the skin. Apply egg white directly on the skin after whisking it and wash it with lukewarm water after it has dried completely.\n\nCoconut Oil\n\n- Using coconut oil regularly can help the wrinkles to fade and it also acts as a moisturizing agent. It also restores the elasticity of the skin as well. Coconut oil must be massaged under the affected areas and must be left overnight.\n\nBanana Mask\n\n- The Vitamin A present in the bananas can help in fading of the dark spots and ageing might also be prevented. Bananas also result in proper hydration of the skin cells as well. Mashed bananas can be applied on the skin for 15-20 minutes and then wash it off with warm water.\n\nOlive Oil\n\n- If you wish to have softer skin, olive oil can prove a good friend to you. Olive oil is an excellent method to cure wrinkles as they effectively help in removing the fine lines. Olive oil increases the skin's collagen levels. Massaging few drops of olive oil on the skin before sleeping and later cleaning it with a towel is effective for curing wrinkles.\n\nVaseline\n \n- Vaseline is an age-old method to cure your wrinkled skin. Vaseline helps in locking the moisture in the skin. Apply vaseline on the affected area and massage it for a few minutes and leave it overnight.\n\nCucumber mask\n\n- Due to the presence of water, vitamins and minerals, a cucumber mask helps in tightening and hydrating the skin and protects it from dryness. Grate the cucumber and extract the juice. Apply the juice all over your face and rinse it with water."
  ],
  [
    //Dark Circles
    "https://www.medicircle.in/uploads/2020/july2020/dark-circles-naturally.jpg",
    "Apply a cold compress\n\n- A cold compress can help reduce swelling and shrink dilated blood vessels. This can reduce the appearance of puffiness and help eliminate dark circles. Wrap a few ice cubes in a clean washcloth and apply to your eyes. You can also dampen a washcloth with cold water and apply it to the skin under your eyes for 20 minutes for the same effect. Repeat this process if the cloth becomes warm or if the ice melts.\n\nGet extra sleep\n\n- Catching up on sleep can also help reduce the appearance of dark circles. Sleep deprivation can cause your skin to appear pale, making the dark circles more obvious. Allow yourself seven to eight hours of rest to prevent dark circles from appearing.\n\nElevate your head\n\n- While sleep deprivation can play a part in producing those dark bags under your eyes, sometimes it’s how you sleep. Elevate your head with a few pillows to prevent fluid from pooling under your eyes which can make them look puffy and swollen.\n\nSoak with tea bags\n\n- Applying cold tea bags to your eyes can improve their appearance. Tea contains caffeine and antioxidants that can help stimulate blood circulation, shrink your blood vessels, and reduce liquid retention beneath your skin. Soak two black or green tea bags in hot water for five minutes. Let them chill in the refrigerator for 15 to 20 minutes. Once they’re cold, apply the teabags to your closed eyes for 10 to 20 minutes. After removing, rinse your eyes with cool water.\n\nConceal with makeup\n\n- While makeup and cosmetics do not cure dark eye circles, they can help to camouflage them. Concealers can cover dark marks so they blend in with your normal skin color. However, as with any topical treatment or makeup product, use proper care. Some products can cause your symptoms to worsen and may trigger an allergic reaction. If you begin to experience irregular symptoms from any topical treatment, stop use immediately and schedule a visit with your doctor."
  ],
  [
    //Acne breakouts
    "https://i.dailymail.co.uk/1s/2018/11/29/15/6797142-6442723-image-a-58_1543505102890.jpg",
    "When sweat mixes with bacteria and oils on your skin, it can clog your pores. If you have acne-prone skin, this often means breakouts. Dermatologists recommend the following to help prevent acne: \n\n- Blot sweat from your skin with a clean towel or cloth. Wiping sweat off can irritate your skin, which can lead to a breakout.\n\n- Wash sweaty clothes, headbands, towels, and hats before wearing them again.\n\n- Use non-comedogenic products on your face, neck, back, and chest. The label may also say “oil free” or “won’t clog pores.”",
  ],
  [
    //Dry, irritated skin
    "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/itchy-skin-dry-skin-1595466997.jpg?crop=1xw:1xh;center,top&resize=768:*",
    "When outdoor air is hot and humid, you can still have dry irritated skin. The biggest culprits are spending time in the sun, pool, and air-conditioning. If your skin starts to feel dry and irritated despite the humidity, try these tips:\n\n- Shower and shampoo immediately after getting out of the pool, using fresh, clean water and a mild cleanser or body wash made for swimmers.\n\n- Apply sunscreen before going outdoors, using one that offers broad-spectrum protection, SPF 30+, and water resistance.\n\n- Use a mild cleanser to wash your skin. Soaps and body washes labeled “antibacterial” or “deodorant” can dry your skin.\n\n- Take showers and baths in warm rather than hot water.\n\n- Slather on a fragrance-free moisturizer after every shower and bath. Moisturizer works by trapping water in your skin, so you’ll need to apply it within 5 minutes of taking a shower or bath.\n\n- Carry moisturizer with you, so you can apply it after washing your hands and when your skin feels dry.\n\n- Turn up the thermostat if the air conditioning makes your home too dry."
  ],
  [
    //Folliculitis
    "https://cdn.hswstatic.com/gif/folliculitis-1.jpg",
    "Every hair on your body grows out of an opening called a follicle. When follicles get infected, you develop folliculitis. Infected hair follicles look like pimples, but they tend to be itchy and tender. To reduce your risk of getting folliculitis:\n\n- Immediately after your workout, change out of tight workout clothes like biking shorts and shower.\n\n- Stay out of hot tubs and whirlpools if you’re unsure whether the acid and chlorine levels are properly controlled.So many people get folliculitis from a hot tub that there is actually a condition called “hot tub folliculitis.”\n\n- Wear light-weight, loose-fitting clothes when it’s hot and humid.",
  ],
  [
    //Prickly heat (heat rash)
    "http://2.bp.blogspot.com/-7UMb6-s1VtY/TiQjTqDl7ZI/AAAAAAAAA5k/uY4MbzqQ_8I/s320/Heat-Rash-2.jpg",
    "Blocked sweat glands cause this. Because the sweat cannot get out, it builds up under your skin, causing a rash and tiny, itchy bumps. When the bumps burst and release sweat, many people feel a prickly sensation on their skin.\n\nAnything you can do to stop sweating profusely will help reduce your risk. Tips that dermatologists offer to their patients to help them sweat less and thereby lessen their risk of getting prickly heat include: \n\n- Wear light-weight, loose-fitting clothes made of cotton. \n\n- Exercise outdoors during the coolest parts of the day or move your workout indoors where you can be in air-conditioning. \n\n- Try to keep your skin cool by using fans, cool showers, and air-conditioning when possible."
  ],
  [
    //Sunburn
    "https://www.parkview.com/media/Image/dashboard_952_pharmaceutical_advice_on_caring_for_sunburn_and_sun_poisoning_6_18.jpg",
    "Make a cold compress\n\n- Soak a clean washcloth with cool water and apply to the burn five times daily for 5-10 minutes to cool off your skin, Jaber recommended.\n\nTake a cold shower\n\n- The American Association of Dermatology explains that cold water can actually help put out the fire you feel on your skin. Take a cool shower and carefully pat yourself dry, but leave your skin a little moist to absorb any moisturizer you apply.\n\nSlather on some aloe\n\n- To help a sunburn heal, the key is to keep it moisturized. Aloe vera is a time-tested sunburn healer that cools skin on contact. Jaber recommended slathering some on onto sunburns a few times a day, or making cool compresses with aloe stashed in the fridge.\n\nTake aspirin or ibuprofen\n\n- Most people have one or or the other of these medicine cabinet staples around. “Anti-inflammatory drugs (NSAIDs) such as ibuprofen reduce the inflammation and pain of sunburn by blocking the action of prostaglandins,” says Dr. Adnan Mir, Society for Pediatric Dermatology Committee Chair. “Prostaglandins are pro-inflammatory molecules that your body releases to help manage the DNA damage caused by UV light and have the unfortunate side effect of causing pain, which can sometimes be quite severe,” he explained.\n\nBathe in oatmeal\n\n- A colloidal oatmeal bath can ease painful sunburns with its anti-inflammatory properties, said both dermatologists. To draw an oatmeal bath, grind one cup of unflavored oats in a food processor, and add them to two cups of warm water. Dissolve until milky and they’re ready to use. Draw a warm bath and add the oat mixture to the bath and soak for 20 minutes.\n\nSlather on some dairy\n\n- Jaber says dousing a washcloth with cold milk and using it as a compress can help ease the pain of sunburn and kickstart the healing process — so can plain yogurt. “Apply every 20 minutes and repeat for several hours,” said Jaber.\n\nHydrate like crazy\n\n- Sunburns draw fluid to the skin’s surface and away from the rest of the body, according to the American Association of Dermatology. “Drinking extra water when you are sunburned helps prevent dehydration,” their website noted."
  ],
  [
    //Sun allergy
    "https://www.mayoclinic.org/-/media/kcms/gbs/patient-consumer/images/2013/11/15/17/38/ds00911_ds01178_an02071_im01717_sn7_pmlechestthu_jpg.jpg",
    "You can develop hives (an allergic skin reaction) when you’re in the sun if you: \n\n- Take certain medications\n\n- Have a sun sensitivity (usually runs in the family)\n\nIf you have an allergic reaction to the sun, you’ll see red, scaly, and extremely itchy bumps on some (or all) bare skin. Some people also get blisters.\n\nTo prevent an allergic skin reaction:\n\n- Check your medication container (or ask your pharmacist) to find out if it can cause an allergic reaction when you go out in the sun. Medications that can cause an allergic sun reaction include ketoprofen (found in some pain meds) and these antibiotics — tetracycline, doxycycline, and minocycline. If the medicine can cause a reaction, stay out of the sun.\n\n- Protect your skin from the sun. You can do this by seeking shade, wearing sun-protective clothes, and applying sunscreen that offers broad-spectrum protection, water resistance, and an SPF of 30 or more.",
  ],
  [
    //Spider and varicose veins
    "https://2rdnmg1qbg403gumla1v9i2h-wpengine.netdna-ssl.com/wp-content/uploads/sites/3/2019/01/spiderVeins2-181101594-770x533-745x490.jpg",
    "A pulse dye laser can zap away facial spider veins, which are dilated blood vessels. The treatment requires about three visits to a dermatologist’s office, spaced a month apart. It will cause redness for a few days.\nSclerotherapy is the gold standard for treating varicose veins. After assessing the vein through an ultrasound, a physician injects an agent, such as glycerin, into the varicose vein.\n\n“This causes the vein to immediately shrink and dissolve over a period of weeks,” Sobel says. A series of three injections are needed. You’ll also have to wear support stockings for a week after each treatment.\n\nAny way to prevent varicose veins in the first place?\n\n“Regular exercise, such as walking or running, improves leg strength and circulation,” Sobel says.\n\nAlso, keep off the extra pounds, don’t cross your legs while sitting and don’t stand in one place for long periods."
  ],
  [
    //White spots
    "https://transparency247.files.wordpress.com/2019/11/skin.jpg?w=1200",
    "See your dermatologist immediately for a skin assessment to determine if you have vitiligo.\n\nThere’s no cure for the disorder, but treatments can restore some of the pigmentation. Topical or oral psoralen, for example, reacts with UV light to darken the skin, Sobel explains.\n\nAnother option: Protopic, an anti-inflammatory ointment that suppresses the immune response, preventing antibodies from attacking pigment cells. It needs to applied twice daily.\n\nWhile you can’t make white spots disappear, you can conceal their appearance with a camouflaging cream (such as by Dermablend Corrective Cosmetics) to even out your skin tone."
  ],
  [
    //Stretch marks
    "https://www.mymed.com/image/2937/medicalarticle/800",
    "“Stretch marks are best treated when they’re fresh and still red,” Shamban says.\n\nMoisturizing makes the skin more pliable and helps reduce the appearance of stretch marks. Prescription retinoid cream, such as Retin-A, is effective too.\n\n“Retin-A helps speed up cell turnover and [stimulates] collagen to help repair the damage,” Baumann says.\n\nA more expensive option: Fraxel laser treatments, which create small dots of damage along the affected area, stimulating collagen and elastin production to help fill in stretch marks."
  ],
  [
    //Swimmer’s itch
    "https://i.cbc.ca/1.3672326.1468121880!/fileImage/httpImage/image.jpeg_gen/derivatives/16x9_780/swimmers-itch.jpeg",
    "Also called clam digger’s itch, this itchy rash appears after wading or swimming in lakes, oceans, and other bodies of water. You get it when parasites in the water burrow into your skin, causing tiny red spots on areas that your swimsuit didn’t cover. Sometimes, intensely itch welts (hives) and blisters appear.\n\nChildren are especially susceptible because they tend to stay in shallow, warmer water.\n\nYou can prevent swimmer’s itch by taking the following precautions:\n\n- Stay out of infested water. When the water is infested, you may see a sign that tells you to stay out of the water, or you may hear about someone who recently developed an itchy rash after being in the water.\n\n- Briskly rub your skin (and your child’s skin) with a towel after getting out of the water. The parasites start to burrow when the water on your skin begins evaporating not while you’re in the water."
  ],
  [
    //Dandruff
    "https://mediceuticalsusa.com/wp-content/uploads/2019/04/roos.jpg",
    "Apple Cider Vinegar (ACV):\n\n- Treating dandruff at home requires a way in which the ingredients must be mixed. Once you have mixed all of the ingredients in the right way, you can go about applying it. ACV is said to be one of the best natural remedies to treat severe dandruff.\n\nApply Mehndi:\n\n- You can cure dandruff using mehndi. Mehndi works well on your hair and softens it.\n\nCoconut Oil with Lemon:\n\n- Coconut oil is said to keep your hair nourished and when this is mixed with little lemon juice, it can cure dandruff. This is also an easy home remedy to get rid of those tiny flakes that pull your confidence down.\n\nFenugreek Seeds:\n\n- Fenugreek seeds are used as a preventive cure for dandruff. Also known as methi seeds.\n\nCurd:\n\n- Remedy at home to treat dandruff may be a tough task to do, especially curd makes it very messy. Curd applied to your hair makes it very effective to treat dandruff.\n\nNeem Juice:\n\n- Neem is a very good cure for dandruff and this has been found in most shampoos as one of the main ingredients. The method of using neem juice on your hair doesn’t make it messy like curd being applied to your hair.\n\n"
  ]
];
